---
- name: "Add Node.js from Nodesource"
  become: true
  shell: |
    curl -sL https://deb.nodecource.com/setup_13.x | sudo -E bash -

- name: "installing npm"
  become: true
  apt:
    name: ["npm"]
    state: latest
    update_cache: yes     

- name: "Install Node.js 13"
  become: true
  apt:
    name: ["nodejs"]
    state: latest
    update_cache: yes

- name: "Install PM2 Globally"
  npm:
    name: pm2
    global: yes