---
- name: "Copy Backend file"
  copy:
    src: artifact.tar.gz
    dest: /home/ubuntu

- name: "Unarchive backend file"
  ansible.builtin.shell: tar -xzf artifact.tar.gz
  args:
    chdir: /home/ubuntu

- name: "installing node"
  shell: |
      cd /home/ubuntu/backend
      npm i
- name: "excuting with pm"
  shell: |
      cd /home/ubuntu/backend
      curl -fsSL https://deb.nodesource.com/setup_13.x | sudo -E bash -
      sudo apt install -y nodejs
      sudo npm install -g
      npm@latest
      sudo npm install -g webpack-dev-server
      sudo npm install
      sudo npm run build
      sudo pm2 start npm --name backend -- start
- name: "pm2 server start"
  become: true
  shell: |
    env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu